server:
  port: 8080
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: tasks_share
  jackson:
    default-property-inclusion: non_null
